// This file is auto-generated by copyWebModules.js. To make permanent changes to it, modify copyWebModules.js
import { Asset } from "expo-asset";

export const webBundleAssets = [
    Asset.fromModule(require("../../assets/web/index.html")),
];
