// This file is auto-generated by copyWebDist.mts. To make permanent changes to it, modify copyWebModules.js
import { Asset } from "expo-asset";

export const webBundleAssets = [
	Asset.fromModule(require("../../assets/web-dist/index-d526a0c5.css")),
	Asset.fromModule(require("../../assets/web-dist/index-fcc6687f.jsAsset")),
	Asset.fromModule(require("../../assets/web-dist/index.html")),
	Asset.fromModule(require("../../assets/web-dist/react-35ef61ed.svg")),
	Asset.fromModule(require("../../assets/web-dist/vite.svg")),
];